import type { City } from "./types/user";

export const CITIES: { id: City; name: string; state: string }[] = [
  { id: "pune", name: "Pune", state: "Maharashtra" },
  { id: "mumbai", name: "Mumbai", state: "Maharashtra" },
  { id: "bangalore", name: "Bangalore", state: "Karnataka" },
  { id: "delhi", name: "Delhi", state: "Delhi" },
  { id: "hyderabad", name: "Hyderabad", state: "Telangana" },
];

export const PROMPTS = [
  { id: "p1", text: "A perfect Sunday looks like...", category: "lifestyle" },
  { id: "p2", text: "My most irrational fear is...", category: "fun" },
  { id: "p3", text: "The way to my heart is...", category: "dating" },
  { id: "p4", text: "I geek out on...", category: "personality" },
  { id: "p5", text: "Two truths and a lie...", category: "fun" },
  { id: "p6", text: "My love language is...", category: "dating" },
  { id: "p7", text: "I'm looking for...", category: "dating" },
  { id: "p8", text: "The best chai in the city is at...", category: "lifestyle" },
  { id: "p9", text: "My go-to karaoke song is...", category: "fun" },
  { id: "p10", text: "I'm convinced that...", category: "personality" },
  { id: "p11", text: "My simple pleasures...", category: "lifestyle" },
  { id: "p12", text: "A life goal of mine is...", category: "personality" },
  { id: "p13", text: "I won't shut up about...", category: "fun" },
  { id: "p14", text: "My ideal first date...", category: "dating" },
  { id: "p15", text: "One thing I'd love to know about you...", category: "dating" },
  { id: "p16", text: "The dorkiest thing about me...", category: "fun" },
  { id: "p17", text: "My comfort food is...", category: "lifestyle" },
  { id: "p18", text: "I feel most alive when...", category: "personality" },
  { id: "p19", text: "Together, we could...", category: "dating" },
  { id: "p20", text: "My weekend plan usually involves...", category: "lifestyle" },
] as const;

export const INTERESTS = [
  "Travel",
  "Photography",
  "Cooking",
  "Fitness",
  "Reading",
  "Music",
  "Movies",
  "Hiking",
  "Coffee",
  "Art",
  "Dancing",
  "Yoga",
  "Gaming",
  "Cricket",
  "Football",
  "Biryani Lover",
  "Dog Person",
  "Cat Person",
  "Foodie",
  "Night Owl",
  "Early Bird",
  "Netflix",
  "Bollywood",
  "Stand-up Comedy",
  "Startups",
  "Meditation",
  "Running",
  "Cycling",
  "Swimming",
  "Poetry",
] as const;

export const COLORS = {
  primary: "#FF6B35",
  secondary: "#EC4899",
  violet: "#7C3AED",
  violetLight: "#B388FF",
  like: "#22C55E",
  nope: "#EF4444",
  superlike: "#3B82F6",
  background: "#FFFFFF",
  backgroundDark: "#171717",
  text: "#171717",
  textDark: "#FAFAFA",
  textSecondary: "#737373",
  border: "#E5E5E5",
  borderDark: "#404040",
} as const;

export const GRADIENTS = {
  primaryToViolet: ["#FF6B35", "#7C3AED"] as const,
  warmSunset: ["#FF6B35", "#EC4899", "#7C3AED"] as const,
  glass: ["rgba(255,255,255,0.15)", "rgba(255,255,255,0.05)"] as const,
  cardOverlay: ["transparent", "rgba(0,0,0,0.65)"] as const,
} as const;
