import type { UserProfile } from "./types/user";
import type { Match, Message } from "./types/match";

const MOCK_PHOTOS = [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&h=800&fit=crop",
];

export const MOCK_PROFILES: UserProfile[] = [
  {
    uid: "user1",
    firstName: "Priya",
    dateOfBirth: "1998-03-15",
    age: 28,
    gender: "woman",
    city: "pune",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[0], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[2], order: 1 },
      { id: "p3", uri: MOCK_PHOTOS[4], order: 2 },
    ],
    prompts: [
      { promptId: "p3", promptText: "The way to my heart is...", answer: "Good conversation over masala chai and a sunset drive on Lavasa road" },
      { promptId: "p8", promptText: "The best chai in the city is at...", answer: "Vohuman Cafe, obviously! Those bun maska & chai combos hit different" },
      { promptId: "p4", promptText: "I geek out on...", answer: "Astronomy, true crime podcasts, and finding the best hidden cafes" },
    ],
    interests: ["Photography", "Coffee", "Travel", "Reading", "Hiking"],
    preferences: { ageMin: 25, ageMax: 33, maxDistance: 25, cities: ["pune"], genderPreference: "men" },
    isVerified: true,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T10:00:00Z",
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    uid: "user2",
    firstName: "Arjun",
    dateOfBirth: "1996-07-22",
    age: 29,
    gender: "man",
    city: "mumbai",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[1], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[3], order: 1 },
      { id: "p3", uri: MOCK_PHOTOS[5], order: 2 },
    ],
    prompts: [
      { promptId: "p1", promptText: "A perfect Sunday looks like...", answer: "Morning run at Marine Drive, brunch at a Bandra cafe, then binge-watching F1" },
      { promptId: "p6", promptText: "My love language is...", answer: "Quality time and cooking dinner together" },
      { promptId: "p13", promptText: "I won't shut up about...", answer: "How Misal Pav is underrated and deserves a Michelin star" },
    ],
    interests: ["Fitness", "Cooking", "Movies", "Cricket", "Music"],
    preferences: { ageMin: 23, ageMax: 30, maxDistance: 30, cities: ["mumbai"], genderPreference: "women" },
    isVerified: true,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T09:00:00Z",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    uid: "user3",
    firstName: "Ananya",
    dateOfBirth: "1999-11-05",
    age: 26,
    gender: "woman",
    city: "bangalore",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[6], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[8], order: 1 },
    ],
    prompts: [
      { promptId: "p7", promptText: "I'm looking for...", answer: "Someone who'll explore Cubbon Park on weekday mornings and debate over filter coffee vs cappuccino" },
      { promptId: "p14", promptText: "My ideal first date...", answer: "Live music at a Koramangala brewery, or a quiet walk in Lalbagh" },
      { promptId: "p11", promptText: "My simple pleasures...", answer: "Rain, a good book, and homemade rasam rice" },
    ],
    interests: ["Yoga", "Art", "Music", "Foodie", "Poetry"],
    preferences: { ageMin: 25, ageMax: 32, maxDistance: 20, cities: ["bangalore"], genderPreference: "men" },
    isVerified: false,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T08:30:00Z",
    createdAt: "2026-03-10T10:00:00Z",
  },
  {
    uid: "user4",
    firstName: "Rohit",
    dateOfBirth: "1995-01-18",
    age: 31,
    gender: "man",
    city: "delhi",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[7], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[9], order: 1 },
      { id: "p3", uri: MOCK_PHOTOS[3], order: 2 },
    ],
    prompts: [
      { promptId: "p10", promptText: "I'm convinced that...", answer: "Delhi has the best street food in the world and I'll fight anyone who disagrees" },
      { promptId: "p17", promptText: "My comfort food is...", answer: "Butter chicken from a specific stall in Chandni Chowk that I'll only reveal on our 3rd date" },
      { promptId: "p19", promptText: "Together, we could...", answer: "Road trip to Jaipur, get lost in old bazaars, and eat way too much" },
    ],
    interests: ["Travel", "Foodie", "Stand-up Comedy", "Football", "Startups"],
    preferences: { ageMin: 22, ageMax: 29, maxDistance: 35, cities: ["delhi"], genderPreference: "women" },
    isVerified: true,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T11:00:00Z",
    createdAt: "2025-12-01T10:00:00Z",
  },
  {
    uid: "user5",
    firstName: "Meera",
    dateOfBirth: "1997-09-30",
    age: 28,
    gender: "woman",
    city: "hyderabad",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[4], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[0], order: 1 },
      { id: "p3", uri: MOCK_PHOTOS[6], order: 2 },
    ],
    prompts: [
      { promptId: "p16", promptText: "The dorkiest thing about me...", answer: "I have a spreadsheet ranking every biryani place in Hyderabad. Yes, it has a weighted scoring system." },
      { promptId: "p18", promptText: "I feel most alive when...", answer: "Dancing at midnight, traveling solo, or having deep conversations with strangers" },
      { promptId: "p15", promptText: "One thing I'd love to know about you...", answer: "What's the most spontaneous thing you've ever done?" },
    ],
    interests: ["Dancing", "Biryani Lover", "Travel", "Netflix", "Meditation"],
    preferences: { ageMin: 26, ageMax: 34, maxDistance: 25, cities: ["hyderabad"], genderPreference: "men" },
    isVerified: true,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T07:00:00Z",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    uid: "user6",
    firstName: "Kavya",
    dateOfBirth: "2000-05-12",
    age: 25,
    gender: "woman",
    city: "pune",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[8], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[2], order: 1 },
    ],
    prompts: [
      { promptId: "p20", promptText: "My weekend plan usually involves...", answer: "FC Road window shopping, then ending up at a quirky bookstore cafe" },
      { promptId: "p9", promptText: "My go-to karaoke song is...", answer: "Tum Hi Ho - I butcher it every time but the passion is there" },
      { promptId: "p2", promptText: "My most irrational fear is...", answer: "Pigeons. Don't ask. Just trust me on this one." },
    ],
    interests: ["Reading", "Coffee", "Bollywood", "Gaming", "Cat Person"],
    preferences: { ageMin: 24, ageMax: 31, maxDistance: 20, cities: ["pune"], genderPreference: "men" },
    isVerified: false,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-15T22:00:00Z",
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    uid: "user7",
    firstName: "Vikram",
    dateOfBirth: "1994-12-08",
    age: 31,
    gender: "man",
    city: "bangalore",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[5], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[1], order: 1 },
      { id: "p3", uri: MOCK_PHOTOS[9], order: 2 },
    ],
    prompts: [
      { promptId: "p12", promptText: "A life goal of mine is...", answer: "Build a sustainable tech company and retire to a coffee estate in Coorg" },
      { promptId: "p5", promptText: "Two truths and a lie...", answer: "I've skydived in Dubai, I can cook a 5-course meal, I've read every Harry Potter book" },
      { promptId: "p3", promptText: "The way to my heart is...", answer: "Good banter, intellectual curiosity, and not being afraid to be silly" },
    ],
    interests: ["Startups", "Coffee", "Running", "Cooking", "Travel"],
    preferences: { ageMin: 23, ageMax: 30, maxDistance: 25, cities: ["bangalore"], genderPreference: "women" },
    isVerified: true,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T12:00:00Z",
    createdAt: "2026-02-14T10:00:00Z",
  },
  {
    uid: "user8",
    firstName: "Isha",
    dateOfBirth: "1998-06-25",
    age: 27,
    gender: "woman",
    city: "mumbai",
    photos: [
      { id: "p1", uri: MOCK_PHOTOS[2], order: 0 },
      { id: "p2", uri: MOCK_PHOTOS[4], order: 1 },
      { id: "p3", uri: MOCK_PHOTOS[8], order: 2 },
    ],
    prompts: [
      { promptId: "p1", promptText: "A perfect Sunday looks like...", answer: "Sunrise yoga at Juhu Beach, then a marathon of cooking experiments while blasting Arijit Singh" },
      { promptId: "p7", promptText: "I'm looking for...", answer: "A fellow dreamer who's also a doer. Bonus points if you can handle Mumbai local trains" },
      { promptId: "p4", promptText: "I geek out on...", answer: "Sustainable fashion, indie music, and conspiracy theories about why Vada Pav costs more than Rs 20 now" },
    ],
    interests: ["Yoga", "Music", "Art", "Cycling", "Foodie"],
    preferences: { ageMin: 26, ageMax: 33, maxDistance: 30, cities: ["mumbai"], genderPreference: "men" },
    isVerified: true,
    isActive: true,
    onboardingComplete: true,
    onboardingStep: 8,
    lastActive: "2026-04-16T06:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    matchId: "user1_currentUser",
    userIds: ["currentUser", "user1"],
    users: {
      user1: { firstName: "Priya", photoUrl: MOCK_PHOTOS[0], age: 28 },
      currentUser: { firstName: "You", photoUrl: MOCK_PHOTOS[1], age: 27 },
    },
    initialLike: { likerId: "currentUser", type: "prompt", comment: "That Vohuman Cafe take is so true!" },
    lastMessage: { text: "Haha yes! We should go there sometime 😄", senderId: "user1", sentAt: "2026-04-16T10:30:00Z" },
    matchedAt: "2026-04-15T14:00:00Z",
    isActive: true,
  },
  {
    matchId: "currentUser_user3",
    userIds: ["currentUser", "user3"],
    users: {
      user3: { firstName: "Ananya", photoUrl: MOCK_PHOTOS[6], age: 26 },
      currentUser: { firstName: "You", photoUrl: MOCK_PHOTOS[1], age: 27 },
    },
    matchedAt: "2026-04-14T18:00:00Z",
    isActive: true,
  },
  {
    matchId: "currentUser_user5",
    userIds: ["currentUser", "user5"],
    users: {
      user5: { firstName: "Meera", photoUrl: MOCK_PHOTOS[4], age: 28 },
      currentUser: { firstName: "You", photoUrl: MOCK_PHOTOS[1], age: 27 },
    },
    lastMessage: { text: "That biryani spreadsheet sounds amazing 😂", senderId: "currentUser", sentAt: "2026-04-13T20:00:00Z" },
    matchedAt: "2026-04-13T12:00:00Z",
    isActive: true,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  user1_currentUser: [
    { messageId: "m1", senderId: "currentUser", text: "Hey Priya! That Vohuman Cafe take is so true! 😄", type: "text", createdAt: "2026-04-15T14:05:00Z" },
    { messageId: "m2", senderId: "user1", text: "Right?! I go there almost every weekend", type: "text", createdAt: "2026-04-15T14:10:00Z" },
    { messageId: "m3", senderId: "currentUser", text: "Same! The bun maska there is unmatched", type: "text", createdAt: "2026-04-15T14:15:00Z" },
    { messageId: "m4", senderId: "user1", text: "Haha yes! We should go there sometime 😄", type: "text", createdAt: "2026-04-16T10:30:00Z" },
  ],
  currentUser_user5: [
    { messageId: "m1", senderId: "currentUser", text: "That biryani spreadsheet sounds amazing 😂", type: "text", createdAt: "2026-04-13T20:00:00Z" },
  ],
};
